#!/bin/tcsh
#PBS -N osmRoadDownload
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=06:30:00
#PBS -j oe

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules
unsetenv PYTHONPATH

conda activate osmDownload

cd /sciclone/geounder/gRoads2/scripts
python pbfDownload.py >& output.out